import time
from colors import aqua, blue, grey, yellow
from utils import clear, generate_title, CENT, LINE


def credits():
    """
    Displays a page that lists the credits and helpful links.
    """
    generate_title(aqua, "Credits")
    time.sleep(0.05)
    print(aqua(CENT("This application wouldn't be possible")))
    time.sleep(0.05)
    print(aqua(CENT("without the brilliant assistance from")))
    time.sleep(0.05)
    print(aqua(CENT("the original lead designer of the 1985")))
    time.sleep(0.05)
    print(aqua(CENT("Apple II version of The Oregon Trail.")))
    time.sleep(0.05)
    print("")
    print(aqua(CENT("R. Philip Bouchard")))
    time.sleep(0.05)
    print(blue(CENT("https://www.philipbouchard.com")))
    print(blue(CENT("https://www.died-of-dysentery.com")))
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(aqua(LINE))
    time.sleep(0.05)
    input(f'{grey(CENT("Press ENTER to continue"))}\n')

    generate_title(aqua, "Credits")
    print(f'\t\t{"Developer:":<15}{aqua("Tim Nelson")}')
    time.sleep(0.05)
    print(f'\t\t{"":<15}{blue("https://github.com/TravelTimN")}')
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(f'\t\t{"Assistance:":<15}{aqua("Chris Quinn")}')
    time.sleep(0.05)
    print(f'\t\t{"":<15}{blue("https://github.com/10xOXR")}')
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(aqua(LINE))
    time.sleep(0.05)
    input(f'{grey(CENT("Press ENTER to continue"))}\n')

    generate_title(aqua, "Credits")
    print(aqua(CENT("Want to play some of the original versions?")))
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(CENT("1980 Old Apple II Version"))
    time.sleep(0.05)
    print(blue(CENT("https://archive.org/details/MECC-A725_Elementary_Vol._6_v1.2")))  # noqa
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(CENT("1985 Classic Apple II Version"))
    time.sleep(0.05)
    print(blue(CENT("https://www.scullinsteel.com/apple2")))
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(CENT("1990 DOS (IBM) Version"))
    time.sleep(0.05)
    print(blue(CENT("https://archive.org/details/msdos_Oregon_Trail_The_1990")))  # noqa
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(CENT('1992 DOS (IBM) "Deluxe" Version'))
    time.sleep(0.05)
    print(blue(CENT("https://archive.org/details/msdos_Oregon_Trail_Deluxe_The_1992")))  # noqa
    time.sleep(0.05)
    print("")
    time.sleep(0.05)
    print(aqua(LINE))
    time.sleep(0.05)
    input(f'{grey(CENT("Press ENTER to continue"))}\n')
